Model Details:
  Organization Name: [Enter the name of the organization of your model (e.g., neuronets, DeepCSR) it has to be the same as the parent folder of your new model.]
  Model Version: [Enter the version of your model (e.g., 1.0, 1.1) it has to be the same as your model's version folder]
  Model Name: [Enter the name of your model. It has to be the same as your model's name folder]
