#### container info
image:
  singularity: nobrainer-zoo_nobrainer.sif
  docker: neuronets/nobrainer-zoo:nobrainer
  
#### repository info
repository:   
    repo_url: "git@github.com:neuronets/nobrainer.git"
    committish: "72aa211b"
    repo_download: False
    repo_download_location: "None"
    
#### required fields for prediction
inference:
    prediction_script: "trained-models/neuronets/kwyk/0.4.1/bwn/predict.py"
    command: f"python3 {MODELS_PATH}/{model}/{model_type}/predict.py -m {model_type} {infile[0]} {outfile}"
    # TODO: we should add help for model options
    options:
      n-samples: {mandatory: False, default: 1, argstr: "-n", type: "int"}
      batch-size: {mandatory: False, default: 8, argstr: "-b", type: "int"}
      save-variance: {argstr: "--save-variance", is_flag: true}
      save-entropy: {argstr: "--save-entropy", is_flag: true}
      overwrite: {mandatory: False, argstr: "--overwrite", type: "str"}
      #atlocation: {argstr: "--atlocation", is_flag: true} # not supported with zoo cli
    #### input data characteristics
    data_spec:
      infile: {n_files: "any"}
      outfile: {n_files: 1}
      
#### required fields for model training 
train:
    #### Not implemented ####      

#### training data characteristics
training_data_info:
    data_number:
        total: 11480
        train: 9184
        evaluate: 1148
        test: 1148
        held_out_data: 418
    biological_sex:
        male: None
        female: None
    age_histogram: None
    race: None
    imaging_contrast_info: "T1-weighted"
    dataset_sources: ["CoRR", "OpenfMRI", "NKI", "SLIM", "ABIDE", "HCP", "ADHD200", "CMI", "SALD", "Buckner", "HBNSSI", "GSP", "Haxby", "Gobbini", "ICBM", "Barrios"]
    data_sites:
        number_of_sites: None
        sites: None
    scanner_models: None
    hardware: None
    training_parameters:
        input_shape: "256x256x256"
        block_shape: "32x32x32"
        n_classes: 50
        lr: 0.0001
        n_epochs: None
        total_batch_size: 32
        number_of_gpus: 4
        loss_function: "Softmax cross-entropy + L2 regularization"
        metrics: "Dice"
        data_preprocessing: "intensity normalization using freesurfer"
        data_augmentation: "No augmentation"

#### model information and help
model:
    model_name: "kwyk"
    description: "3D brain segmentation model"
    structure: "Meshnet"
    training_mode: "supervised"
    model_url: "https://github.com/neuronets/kwyk"
    Zoo_function: "predict"
    example: "nobrainer-zoo predict -m neuronets/kwyk/0.4.0 --model_type bwn <path_to_input> <path_to_output>/out"
    note: "output will be saved as .nii.gz file type (e.g out_means.nii.gz)"
    input_file_type: "nii.gz"
    model_details: ""
    intended_use: ""
    factors: ""
    metrics: ""
    eval_data: ""
    training_data: ""
    quant_analyses: ""
    ethical_considerations: ""
    caveats_recs: ""