#### container info
image:
  singularity: nobrainer-zoo_nobrainer.sif
  docker: neuronets/nobrainer-zoo:nobrainer
  
#### repository info
repository:   
    repo_url: "git@github.com:neuronets/nobrainer.git"
    committish: "72aa211b"
    repo_download: False
    repo_download_location: "None"
    
#### required fields for prediction
inference:
    prediction_script: "trained-models/neuronets/braingen/0.1.0/generator_res_128/generate.py"
    command: f"python3 {MODELS_PATH}/{model}/{model_type}/generate.py -m {model_path} {outfile}"
    # TODO: we should add help for model options
    options:
      latent-size: {mandatory: False, default: 1024, argstr: "-l", type: "int"}
      drange-in: {mandatory: False, default: (-1, 1), argstr: "--drange-in", type: "int"}
      drange-out: {mandatory: False, default: (0, 255), argstr: "--drange-out", type: "int"}
      output-shape: {mandatory: False, default: (128, 128, 128), argstr: "-o", type: "int"}
      verbose: {argstr: "-v", is_flag: true}
    #### input data characteristics
    data_spec:
      outfile: {n_files: 1}
      
#### required fields for model training
train:
#### TODO: Add the train spec here
#### training data characteristics
training_data_info:
    data_number:
        total: None
        train: None
        evaluate: None
        test: None
    biological_sex:
        male: None
        female: None
    age_histogram: None
    race: None
    imaging_contrast_info: "T1-weighted"
    dataset_sources: None
    data_sites:
        number_of_sites: None
        sites: None
    scanner_models: None
    hardware: None
    training_parameters:
        input_shape: None
        block_shape: "128x128x128"
        n_classes: None
        lr: None
        n_epochs: None
        total_batch_size: None
        number_of_gpus: None
        loss_function: None
        metrics: None
        data_preprocessing: None
        data_augmentation: None

#### model information and help
model:
    model_name: "braingen"
    description: "3D brain generator model at 128 cube."
    structure: "GAN"
    training_mode: "unsupervised"
    model_url: "https://github.com/neuronets/progressivegan3d"
    Zoo_function: "generate"
    example: "nobrainer-zoo generate -m neuronets/braingen/0.1.0 --model_type generator_res_128 <path_to_output>/out.nii.gz"
    note: "Please provide an output file name with an extension."
    input_file_type: None
    model_details: ""
    intended_use: ""
    factors: ""
    metrics: ""
    eval_data: ""
    training_data: ""
    quant_analyses: ""
    ethical_considerations: ""
    caveats_recs: ""