#### container info
image:
  singularity: nobrainer-zoo_ddig.sif
  docker: neuronets/nobrainer-zoo:ddig

#### repository info
repository:  
    repo_url: "https://github.com/voxelmorph/voxelmorph.git"
    committish: "67bc9d20"
    repo_download: False
    repo_download_location: "None"

#### required fields for prediction
inference:
    prediction_script: "trained-models/DDIG/SynthMorph/1.0.0/brains/register.py"
    command: f"python3 {MODELS_PATH}/{model}/{model_type}/register.py --moving {moving} --fixed {fixed} --model {model_path} --moved {moved}"
    # TODO: we should add help for model options
    options:
      warp: {mandatory: False, argstr: "--warp", type: "str"}  
      gpu: {mandatory: False, default: "None", argstr: "--gpu", type: "int"}
      multichannel: {mandatory: False, is_flag: true} 
    #### input data characteristics
    data_spec:
      moving: {n_files: 1}
      fixed: {n_files: 1}
      moved: {n_files: 1}
      
#### required fields for model training 
train:
    # TODO: train spec to be added

#### training data characteristics
training_data_info:
    data_number:
        total: None
        train: None
        evaluate: None
        test: None
    biological_sex:
        male: None
        female: None
    age_histogram: None
    race: None
    imaging_contrast_info: None
    dataset_sources: None
    data_sites:
        number_of_sites: None
        sites: None
    scanner_models: None
    hardware: None
    training_parameters:
        input_shape: None
        block_shape: None
        n_classes: None
        lr: None
        n_epochs: None
        total_batch_size: None
        number_of_gpus: None
        loss_function: None
        metrics: None
        data_preprocessing: None
        data_augmentation: None
