#### container info
image:
  singularity: nobrainer-zoo_ucl.sif
  docker: neuronets/nobrainer-zoo:ucl
  
#### repository info
repository:  
    repo_url: "https://github.com/BBillot/SynthSR.git"
    committish: "59b92b54"
    repo_download: True
    repo_download_location: f"{REPO_PATH}/{model_nm}-{ver}"
    
#### required fields for prediction
inference:
    prediction_script: "trained-models/UCL/SynthSR/1.0.0/hyperfine/predict.py" 
    command: f"python3 {MODELS_PATH}/{model}/{model_type}/predict.py --repo_path {repo_dest} --model_path {model_path} {infile[0]} {infile[1]} {outfile}"
    # TODO: we should add help for options.
    options:
      threads: {mandatory: False, argstr: "--threads", type: "int", default: 1}
      cpu: {mandatory: False, argstr: "--cpu", is_flag: true}
    #### input data characteristics
    data_spec:
      infile: {n_files: 2}
      outfile: {n_files: 1}
      
#### training data characteristics
training_data_info:
    data_number:
        total: None
        train: None
        evaluate: None
        test: None
    biological_sex:
        male: None
        female: None
    age_histogram: None
    race: None
    imaging_contrast_info: "any contrast"
    dataset_sources: None
    data_sites:
        number_of_sites: None
        sites: None
    scanner_models: None
    hardware: None
    training_parameters:
        input_shape: None
        block_shape: None
        n_classes: None
        lr: None
        n_epochs: None
        total_batch_size: None
        number_of_gpus: None
        loss_function: None
        metrics: None
        data_preprocessing: None
        data_augmentation: "spatial transform"

#### model information and help
model:
    model_name: "SynthSR"
    description: "3D brain hyper resolution model"
    structure: "U-Net"
    training_mode: None
    model_url: "https://github.com/BBillot/SynthSR"
    Zoo_function: "predict"
    example: "nobrainer-zoo predict -m UCL/SynthSR/1.0.0 --model_type hyperfine <path_to_input_T1> <path_to_input_T2> <path_to_output>/out.nii.gz"
    note: "Please provide an output file name with an extension."
    input_file_type: "nii.gz"
    model_details: ""
    intended_use: ""
    factors: ""
    metrics: ""
    eval_data: ""
    training_data: ""
    quant_analyses: ""
    ethical_considerations: ""
    caveats_recs: ""