#### container info
image:
  singularity: nobrainer-zoo_ucl.sif
  docker: neuronets/nobrainer-zoo:ucl

#### repository info
repository:  
    repo_url: "https://github.com/BBillot/SynthSeg.git"
    committish: "cd597b08"
    repo_download: True
    repo_download_location: f"{REPO_PATH}/{model_nm}-{ver}"
    
#### required fields for prediction
inference:
    prediction_script: "trained-models/UCL/SynthSeg/1.0.0/predict.py"
    command: f"python3 {MODELS_PATH}/{model}/predict.py --repo_path {repo_dest} --model_path {model_path} --i {infile[0]} --o {outfile}"
    # TODO: we should add help for options.
    options: 
      post: {mandatory: False, argstr: "--post", type: "str"}
      resample: {mandatory: False, argstr: "--resample", type: "str"}
      vol: {mandatury: False, argstr: "--vol", type: "str"}
      crop: {mandatory: False, argstr: "--crop", type: "int", default: 192}
      threads: {mandatory: False, argstr: "--threads", type: "int", default: 1}
      cpu: {mandatory: False, argstr: "--cpu", is_flag: true}
    #### input data characteristics
    data_spec:
      infile: {n_files: 1}
      outfile: {n_files: 1}
      
#### training data characteristics
training_data_info:
    data_number:
        total: None
        train: None
        evaluate: None
        test: None
    biological_sex:
        male: None
        female: None
    age_histogram: None
    race: None
    imaging_contrast_info: "any contrast"
    dataset_sources: None
    data_sites:
        number_of_sites: None
        sites: None
    scanner_models: None
    hardware: None
    training_parameters:
        input_shape: None
        block_shape: None
        n_classes: None
        lr: None
        n_epochs: None
        total_batch_size: None
        number_of_gpus: None
        loss_function: None
        metrics: None
        data_preprocessing: None
        data_augmentation: "domain randomization using a generator"

#### model information and help
model:
    model_name: "SynthSeg"
    description: "3D brain segmentation model"
    structure: "U-Net"
    training_mode: "supervised"
    model_url: "https://github.com/BBillot/SynthSeg"
    Zoo_function: "predict"
    example: "nobrainer-zoo predict -m UCL/SynthSeg/1.0.0 <path_to_input> <path_to_output>/out.nii.gz"
    note: "Please provide an output file name with an extension."
    input_file_type: "nii.gz"
    model_details: ""
    intended_use: ""
    factors: ""
    metrics: ""
    eval_data: ""
    training_data: ""
    quant_analyses: ""
    ethical_considerations: ""
    caveats_recs: ""