name: Update label for issues

on: 
  issues:
    types:
      - edited

jobs:
  update_label:
    if: ${{ (startsWith(github.event.issue.title, 'New Model:') || startsWith(github.event.issue.title, 'Update Model:')) }}

    runs-on: ubuntu-latest

    steps:
      - name: Set labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'set-labels'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Ready-to-test'