name: Get Model Data

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Clone trained-models-template
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'neuronets'
          repository: 'trained-models-template'

      - name: Move package-lock.json to root
        run: mv ./.github/workflows/package-lock.json ./package-lock.json

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci

      - name: Run get_model_data.js
        run: node ./.github/workflows/get_model_data.js

      - name: Extract files from clone and remove clone
        run: |
          mv ./trained-models-template/docs .
          rm -r ./trained-models-template

      - name: Push to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          push_options: '--force'
          skip_checkout: true