name: Get Model Data

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - name: Run get_model_data script
        run: node ./.github/workflows/get_model_data.js