name: Get Model Data

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Run get_model_data script
        run: node ./.github/workflows/get_model_data.js

      - name: Sleep for 30 seconds
        uses: whatnick/wait-action@master
        with:
          time: '30s'

      - name: check for changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            data:
              - 'docs/_data/**'
              - 'docs/_pages/**'

      - name: stage changed files
        if: steps.changes.outputs.data == 'true'
        run: git add docs/*

      - name: commit changed files
        if: steps.changes.outputs.data == 'true'
        run: git commit -m "Auto updating docs/"
      
      - name: fetch from master
        if: steps.changes.outputs.data == 'true'
        run: git fetch origin master

      - name: push code to master
        if: steps.changes.outputs.data == 'true'
        run: git push origin HEAD:master