name: Get Model Data

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Run get_model_data script
        run: node ./.github/workflows/get_model_data.js

      - uses: stefanzweifel/git-auto-commit-action@v4