name: Run Script

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - name: Run the script
        run: node ./.github/workflows/script.js